In [1]:
# libraries
import pandas as pd

# fbref table link
url_df = 'https://fbref.com/en/comps/Big5/gca/players/Big-5-European-Leagues-Stats#stats_gca'

df = pd.read_html(url_df)
df

[     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                      Rk             Player             Nation
 0                     1         Max Aarons            eng ENG
 1                     2   Brenden Aaronson             us USA
 2                     3    Paxten Aaronson             us USA
 3                     4  Keyliane Abdallah             fr FRA
 4                     5   Yunis Abdelhamid             ma MAR
 ...                 ...                ...                ...
 2962               2850    Martin Ødegaard             no NOR
 2963                 Rk             Player             Nation
 2964               2851        Milan Đurić             ba BIH
 2965               2852        Milan Đurić             ba BIH
 2966               2853   Mateusz Łęgowski             pl POL

      Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                     Pos              Squad                Comp
 0                    DF        Bournemouth  eng Premier League
 1                 MF,FW       Union Berlin       de Bundesliga
 2                    MF     Eint Frankfurt       de Bundesliga
 3                    FW          Marseille          fr Ligue 1
 4                    DF              Reims          fr Ligue 1
 ...                 ...                ...                 ...
 2962                 MF            Arsenal  eng Premier League
 2963                Pos              Squad                Comp
 2964                 FW      Hellas Verona          it Serie A
 2965                 FW              Monza          it Serie A
 2966                 MF        Salernitana          it Serie A

      Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0  SCA  ...  \
                     Age               Born                90s  SCA  ...
 0                    23               2000               13.7   23  ...
 1                    22               2000               14.1   53  ...
 2                    19               2003                1.1    1  ...
 3                    17               2006                0.0    0  ...
 4                    35               1987               30.9   24  ...
 ...                 ...                ...                ...  ...  ...
 2962                 24               1998               34.3  220  ...
 2963                Age               Born                90s  SCA  ...
 2964                 33               1990               13.4   33  ...
 2965                 33               1990               14.0   13  ...
 2966                 20               2003               12.7   18  ...

      SCA Types  GCA        GCA Types                              \
            Def  GCA  GCA90  PassLive  PassDead  TO  Sh  Fld  Def
 0            0    2   0.15         2         0   0   0    0    0
 1            0    8   0.57         6         0   2   0    0    0
 2            0    1   0.89         1         0   0   0    0    0
 3            0    0   0.00         0         0   0   0    0    0
 4            0    1   0.03         0         0   0   1    0    0
 ...        ...  ...    ...       ...       ...  ..  ..  ...  ...
 2962         1   23   0.67        18         2   0   2    1    0
 2963       Def  GCA  GCA90  PassLive  PassDead  TO  Sh  Fld  Def
 2964         1    4   0.30         1         0   0   0    2    1
 2965         0    1   0.07         1         0   0   0    0    0
 2966         1    0   0.00         0         0   0   0    0    0

      Unnamed: 25_level_0
                  Matches
 0                Matches
 1                Matches
 2                Matches
 3                Matches
 4                Matches
 ...                  ...
 2962             Matches
 2963             Matches
 2964             Matches
 2965             Matches
 2966             Matches

 [2967 rows x 26 columns]]

In [2]:
df = pd.read_html(url_df)[0]
df.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player             Nation                Pos
0                  1         Max Aarons            eng ENG                 DF
1                  2   Brenden Aaronson             us USA              MF,FW
2                  3    Paxten Aaronson             us USA                 MF
3                  4  Keyliane Abdallah             fr FRA                 FW
4                  5   Yunis Abdelhamid             ma MAR                 DF

  Unnamed: 4_level_0  Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Squad                Comp                Age
0        Bournemouth  eng Premier League                 23
1       Union Berlin       de Bundesliga                 22
2     Eint Frankfurt       de Bundesliga                 19
3          Marseille          fr Ligue 1                 17
4              Reims          fr Ligue 1                 35

  Unnamed: 7_level_0 Unnamed: 8_level_0 SCA  ... SCA Types GCA        \
                Born                90s SCA  ...       Def GCA GCA90
0               2000               13.7  23  ...         0   2  0.15
1               2000               14.1  53  ...         0   8  0.57
2               2003                1.1   1  ...         0   1  0.89
3               2006                0.0   0  ...         0   0  0.00
4               1987               30.9  24  ...         0   1  0.03

  GCA Types                        Unnamed: 25_level_0
   PassLive PassDead TO Sh Fld Def             Matches
0         2        0  0  0   0   0             Matches
1         6        0  2  0   0   0             Matches
2         1        0  0  0   0   0             Matches
3         0        0  0  0   0   0             Matches
4         0        0  0  1   0   0             Matches

[5 rows x 26 columns]

In [3]:
# creating a data with the same headers but without multi indexing
df.columns = [' '.join(col).strip() for col in df.columns]

df = df.reset_index(drop=True)
df.head()

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Player,Unnamed: 2_level_0 Nation,Unnamed: 3_level_0 Pos,Unnamed: 4_level_0 Squad,Unnamed: 5_level_0 Comp,Unnamed: 6_level_0 Age,Unnamed: 7_level_0 Born,Unnamed: 8_level_0 90s,SCA SCA,...,SCA Types Def,GCA GCA,GCA GCA90,GCA Types PassLive,GCA Types PassDead,GCA Types TO,GCA Types Sh,GCA Types Fld,GCA Types Def,Unnamed: 25_level_0 Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,23,...,0,2,0.15,2,0,0,0,0,0,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,53,...,0,8,0.57,6,0,2,0,0,0,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,1,...,0,1,0.89,1,0,0,0,0,0,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,0,...,0,0,0.00,0,0,0,0,0,0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,24,...,0,1,0.03,0,0,0,1,0,0,Matches

In [4]:
# creating a list with new names
new_columns = []
for col in df.columns:
  if 'level_0' in col:
      new_col = col.split()[-1]  # takes the last name
  else:
      new_col = col
  new_columns.append(new_col)

# rename columns
df.columns = new_columns
df = df.fillna(0)

df.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,SCA SCA,...,SCA Types Def,GCA GCA,GCA GCA90,GCA Types PassLive,GCA Types PassDead,GCA Types TO,GCA Types Sh,GCA Types Fld,GCA Types Def,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,23,...,0,2,0.15,2,0,0,0,0,0,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,53,...,0,8,0.57,6,0,2,0,0,0,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,1,...,0,1,0.89,1,0,0,0,0,0,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,0,...,0,0,0.00,0,0,0,0,0,0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,24,...,0,1,0.03,0,0,0,1,0,0,Matches

In [5]:
df['Age'] = df['Age'].str[:2]
df['Position_2'] = df['Pos'].str[3:]
df['Position'] = df['Pos'].str[:2]
df['Nation'] = df['Nation'].str.split(' ').str.get(1)
df['League'] = df['Comp'].str.split(' ').str.get(1)
df['League_'] = df['Comp'].str.split(' ').str.get(2)
df['League'] = df['League'] + ' ' + df['League_']
df = df.drop(columns=['League_', 'Comp', 'Rk', 'Pos','Matches'])

df['Position'] = df['Position'].replace({'MF': 'Midfielder', 'DF': 'Defender', 'FW': 'Forward', 'GK': 'Goalkeeper'})
df['Position_2'] = df['Position_2'].replace({'MF': 'Midfielder', 'DF': 'Defender',
                                                 'FW': 'Forward', 'GK': 'Goalkeeper'})
df['League'] = df['League'].fillna('Bundesliga')

In [9]:
# df.head()
print(df["League"].unique())

['Premier League' 'Bundesliga' 'Ligue 1' 'La Liga' 'Serie A']

In [10]:
df.to_csv("best5leagues_datasetplayers.csv", index=False)